version: '3' 
services: 
 web:
   network_mode: host 
   build: . 
   command: python3 /app/app.py 
   volumes: 
   - .:/app 
   ports: 
   - "5000:5000"
   expose:
   - "5000"
   extra_hosts:
    - "host.docker.internal:host-gateway"